### ISSUE TITLE
Decide on dashboard

### ISSUE THREAD

**Issue by samcunliffe** [SainsburyWellcomeCentre/WAZP#1]
Stress test and try out for ease of use and ease of development. Then make a choice.

## Considerations: 
* the ability to stream several videos,
* slider and interface design requirements from PIs,

## Candidates:
- [ ] Voila (ease to port from jupyter notebook)
- [ ] Plotly + dash
- [ ] Streamlit ←
- [ ] [Google/neuroglancer](https://github.com/google/neuroglancer) (perhaps too focused on volumetric).
- [ ] Zooniverse
- [ ] ....

**Comment by samcunliffe** [comment]
https://panel.holoviz.org/ was suggested by someone in ARC.

**Comment by sfmig** [comment]
someone from SWC recommended Dash/Plotly and has a demo we can check (from inside SWC)

**Comment by sfmig** [comment]
I think Dash/Plotly or Streamlit are the best two options. I found a good comparison between them  [here](https://www.datarevenue.com/en-blog/data-dashboarding-streamlit-vs-dash-vs-shiny-vs-voila#:~:text=Streamlit%20is%20more%20structured%20and,Dash%20is%20more%20adaptable.)

Some key differences:

Dash/Plotly  
- around for longer, larger community
- steeper learning curve
- potentially more flexible?
- more focused on production/industry applications?
- primarily designed to work with Plotly
- example with video data [here](https://github.com/plotly/dash-sample-apps/tree/main/apps/dash-video-detection) 

Streamlit
- fairly straightforward
- easy to prototype
- may be limited/less flexible?
- example with video data [here](https://github.com/plotly/dash-sample-apps/tree/main/apps/dash-video-detection)
- more flexible wrt underlying plotting library (matplotlib, seaborn etc)
- worse speed performance: the whole app is re-run when input changes

Feel free to post below any thoughts

**Comment by adamltyson** [comment]
@samcunliffe those two links are both for dash btw.

> worse speed performance: the whole app is re-run when input changes

What does this mean in practice? If we change e.g. a parameter, does the whole thing reload?

**Comment by niksirbi** [comment]
Thanks @sfmig for the report. 
After reading that very helpful article, I'm also leaning towards Dash, with Streamlit as 2nd option.
Though Streamlit sounds like it would get us to our prototype/MVP the fastest, I'm worried that it's limited customisability/generality (is that even a word?) will cause us headaches down the line when we extend the pipeline.

My only issue with Dash is the following:
> Although they’re both open source, Dash is more focused on the enterprise market and doesn’t include all the features (such as job queues) in the open source version. By contrast, Streamlit is fully open source. 
Though I don't know if we would actually need the Dash enterprise feature.

Another plus for Dash (for me) is that it also has R and Julia support, so it seems like a more generally useful tool to invest into learning.

The link to the Streamlit video data example wrongly leads to the Dash example

**Comment by sfmig** [comment]
Fixed the duplicate link. I didnt't find a good repo of streamlit with video but it seems easy from the snippet.

**Comment by sfmig** [comment]
I am happy to close this issue and continue forward with Dash/Plotly, but feel free to re-open if you think otherwise
