### ISSUE TITLE
How are the videos split?

### ISSUE THREAD

**Issue by samcunliffe** [SainsburyWellcomeCentre/WAZP#15]
Is it one video split into (i.e. continuous acquisition split up by experimental conditions)? Or is it separated by "changeover time"?

**Comment by niksirbi** [comment]
So, for all jewel wasp experiments done up to date, the splitting happens during data acquisition and is manually triggered by the experimenter when the experimental condition changes (essentially amounting to 'send data from now on to new video file'). In practice, this results to only a few ms loss between the videos within a session. 
Experimenters plan a switch to acquiring one continuous video for future sessions. Given that. the existing videos may be merged within session (if the few ms of discontinuity between experimental conditions can be ignored).

**Comment by sfmig** [comment]
we had a chat with Sanna today that clarified this further. For the wasp data we assume that if any data is lost between videos of the same session, this is negligible. Closing this issue for now.
