### ISSUE TITLE
Hosting data for testing

### ISSUE THREAD

**Issue by sfmig** [SainsburyWellcomeCentre/WAZP#33]
For now, simply adding metadata files, video aliases and pose estimation results (h5) to the repo. See discussion [here](https://github.com/SainsburyWellcomeCentre/WAZP/pull/29#issuecomment-1420616670). 

Better alternatives: 
- Zenodo
- [Github LFS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository)

We need to check with T&T if alright to host a subset of data publicly. 

I assigned it to all of us for now to keep everyone in the loop, but I'm happy to get started on this one.

**Comment by adamltyson** [comment]
Following a conversation with Niko, I would argue that the real datasets shouldn't be stored in (or associated with) this repository.

The way that I would normally work on projects such as this is:

For development, manual testing and debugging, I would have a "representative" dataset (or >1) stored locally. This would be real data, full size videos etc. This could be hosted online to allow other devs to download is more easily, but crucially the path to this isn't stored in the repository, and is passed in (as an arg, via the GUI, whatever makes sense for the specific app and the developers workflow). 

For automated testing, the smallest possible version of the above, so I would reduce the number of videos, downsample them, crop them etc. The structure of the project would remain, but the file sizes would be so small that they can be stored in the repo itself.

**Comment by samcunliffe** [comment]
+1. I agree with that.

Our `sample_project` is the representative one, right? So we could put it on Git LFS anyway? Or should we just share between us via the SWC fileshare? (Perhaps that's the smarter solution now I'm thinking a bit more about it.)

For CI integration testing purposes, I'd guess something like 2 10-frame videos (+ metadata) would be more than sufficient. Was kind of thinking we'd just open it, load/draw an ROI and define *an* event marker and check there are no errors (#27).

**Comment by niksirbi** [comment]
> Our `sample_project` is the representative one, right? So we could put it on Git LFS anyway? Or should we just share between us via the SWC fileshare? (Perhaps that's the smarter solution now I'm thinking a bit more about it.)

In a way we already have that shared, in the sense that the original data is in SWC `/ceph/zoo`. However that copy doesn't contain the metadata yaml files and we don't want to mess with that during dev anyway. Could we have it on sth like UCL dropbox for quick and easy access by developers?

> For CI integration testing purposes, I'd guess something like 2 10-frame videos (+ metadata) would be more than sufficient. Was kind of thinking we'd just open it, load/draw an ROI and define _an_ event marker and check there are no errors (#27).

Agreed.

**Comment by niksirbi** [comment]
Yeah, they are just aliases, which means each developer would have to link them to wherever they have them (which is an awkward solution)

**Comment by sfmig** [comment]
Consider using pooch 🐶 
See example [here](https://github.com/brainglobe/brainreg-napari/blob/68c369eb8db019c1571ba29740a37d1cdc5879f5/brainreg_napari/sample_data.py#L12-L21)
