### ISSUE TITLE
add ROI in the exported dataframe

### ISSUE THREAD

**Issue by sfmig** [SainsburyWellcomeCentre/WAZP#40]
For now, the ROI label is just an empty string, but the idea would be to read the ROI path from the video metadata file and check if a bodypart at a specific frame is inside the ROI.

@niksirbi I assign you too since you have more experience reading ROI paths and using the library to check if a point is inside, but happy to work on it together if you want.

**Comment by niksirbi** [comment]
Happy to take a look at that. I guess the idea is to do that after #28 and #38 are merged?
