### ISSUE TITLE
small additions to ROI tab

### ISSUE THREAD

**Issue by sfmig** [SainsburyWellcomeCentre/WAZP#44]
I added a post-hoc review to the ROI PR. 

Most are minor comments, the main suggestion is about the layout of the components. I leave a link to the start of the review [here](https://github.com/SainsburyWellcomeCentre/WAZP/pull/28#pullrequestreview-1321942288).

Two additional thoughts that came to mind while playing with it*:
- is it possible to delete a shape easily? I saw you and @samcunliffe also discussed this, and I liked that option of deleting a row that you suggested.
- is there a message if you click load ROIs and there is nothing stored in the metadata for that video? Should we signal to the user if data is available for a video as soon as it is selected in the dropdown?

*I couldn't play too much with it because I had issues with ceph and couldn't download a sample video 😢 . Hence the second question.

**Comment by niksirbi** [comment]
Thanks for the comments Sofia. Can't get these done by Monday, but can tackle these in the next "on week"

## Deleting a shape
I will experiment with allowing the user to delete a table row. Maybe it won't complicate the callback too much

## Inform the user about the presence of ROIs in the metadata file
That's actually a cool idea. I could either:
* Just inform the user whether ROIs can be found in the metadata whenever they select a video (and prompt them to load the ROIs, if yes)
* Automatically load saved ROIs from file, whenever a video is selected.

I personally prefer the first option, as it leaves the choice to the user.
