### ISSUE TITLE
loading the dashboard and file paths of the home page

### ISSUE THREAD

**Issue by sannatitus** [SainsburyWellcomeCentre/WAZP#83]
Hey team!

So sorry that it's taken ages to get some user feedback for the WAZP dashboard. Thank you to all of you who worked so hard on it - it's very much appreciated! It doesn't seem like I'm using it now, but I've been very busy with onboarding two new crab folks, having a new zoo director, and a new tight deadline at the zoo :( I've just started to mess around with the dashboard formally today, but unfortunately won't be able to have a good play with it until mid May. I'll be focused nearly entirely on data acquisition until mid June - so sorry about this! 
The first and main issue I've come across is loading the input_config.yaml. The first drag & drop typically works well, but if I navigate elsewhere and return to the dashboard, I get these callback errors:
![1](https://user-images.githubusercontent.com/100142813/234019325-d0b27404-23b1-45ac-a94f-4efa4432781c.PNG)

Also, when attempting to load another input_config.yaml, it doesn't actually load it (I tried both drag & drop and going through the file explorer menu) and it rather states the file path of the original input_config.yaml: 
![wrong-file-path-2](https://user-images.githubusercontent.com/100142813/234019380-1a7acbba-7e2a-4ed4-9b3d-ca63fed46ec4.PNG)
![wrong-file-path-3](https://user-images.githubusercontent.com/100142813/234019386-1e09221b-df24-40be-ad2a-822852bcad4b.PNG)
![wrong-file-path-1](https://user-images.githubusercontent.com/100142813/234019389-478e7a08-857c-4b5c-99da-cbeee8621cc6.PNG) ). I'm making this post together as it seems these two issues may be related. Or, for the second issue, do I just have to close the dashboard and reopen the cmd's http link again if I want to switch input_config.yamls? 

Cheers :)

**Comment by sannatitus** [comment]
I haven't had any issues like this today and I've thrown ~20 input_config.yaml's in there :-) 
I think we can complete this issue?

**Comment by samcunliffe** [comment]
Thanks @sannatitus 

There's a minor change which relates to this that just suppresses the error when you go there with no config (the first part). That will be in v0.2 (when we make it).
