### ISSUE TITLE
defining ROIs

### ISSUE THREAD

**Issue by sannatitus** [SainsburyWellcomeCentre/WAZP#84]
Perhaps we should only allow each ROI name to have one ROI designation?

It seems like I can draw multipe ROIs which all are saved as 'enclosure'... how do I know which coordinates WAZP is using to compare to the DLC dataset? It might be easiest for the user if the new ROI drawing simply overwrites the old one, with the possibility to undo or view your former drawings. But with this setup, it's not clear to me on the GUI which enclosure ROI is actually being used 
![4](https://user-images.githubusercontent.com/100142813/234021638-04e18f2c-c0bd-44de-ad8f-16feca7ce35e.PNG)

**Comment by sannatitus** [comment]
please enjoy my ugly circle blobs. trying to keep you on your toes ;)

**Comment by niksirbi** [comment]
Thanks, @sannatitus. These are both excellent points, and they should be straightforward to fix (famous last words).
So I will try to:
- [ ] enforce only 1 ROI shape per ROI name
- [ ] automatically shift to next ROI name after the previous one is drawn

**Comment by niksirbi** [comment]
@sannatitus 
Here are the changes I made:

> The ROIs that have been already drawn disappear from the dropdown. They can be still edited and deleted (in this last case, the ROI name will reappear in the dropdown).
> Every time an ROI is drawn, the dropdown value automatically updates to the next ROI that needs drawing.
> If all ROIs have been drawn, the dropdown lets the user know, and the drawing of new shapes is disabled

Let us know if the current behaviour suits your workflow. Otherwise, we can reopen the issue.
