### ISSUE TITLE
ignore this :) 

### ISSUE THREAD

**Issue by sannatitus** [SainsburyWellcomeCentre/WAZP#93]
Hi all,
I created an issue because I got an error about a missing metadata_fields.yaml; however, I found Sofia's lovely file [here](https://github.com/SainsburyWellcomeCentre/WAZP/blob/89f0e287dcf12992c8d74228b53d547e4bdcfd0b/sample_project/metadata_fields.yaml) which worked! 
So this issue is sorted, but I don't seem to have permissions to delete the chain... 
Cheers
S

**Comment by samcunliffe** [comment]
I don't think there is such a thing as deleting of tickets.
We can just close it and give @sfmig the kudos (since she already fixed it).
